- alias: Trigger eetkamer tafel lamp On
  description: ''
  
  trigger:
  - platform: state
    entity_id: switch.schakelaar_eetkamer   
    to: 'on'    
    
  action:
    service: homeassistant.turn_on
    entity_id: 
       - light.eetkamer


######################################################################
- alias: Turn off eetkamer tafel door schakelaar
  trigger:
    - platform: state
      entity_id: switch.schakelaar_eetkamer
      to: 'off'     
      
  action:
    service: homeassistant.turn_off
    entity_id: light.eetkamer
    
