---
- alias: Trigger WC
  description: ""
  trigger:
    - platform: state
      entity_id:
        - binary_sensor.motion_wc
      from: "off"
      to: "on"
  condition: []

  action:
    - service: homeassistant.turn_on
      data: {}
      target:
        entity_id: switch.schakelaar_wc

    - wait_for_trigger:
        - platform: state
          entity_id:
            - binary_sensor.motion_wc
          from: "on"
          to: "off"
          for:
            hours: 0
            minutes: 2
            seconds: 0

    - service: homeassistant.turn_off
      data: {}
      target:
        entity_id: switch.schakelaar_wc

  mode: single
