- alias: Trigger Trap Schakelaar Links on
  description: ""
  trigger:
    - entity_id: switch.trap_schakelaar_links
      platform: state
      to: "on"
  condition: []
  action:
    - service: homeassistant.turn_on
      entity_id: group.lampen_boven

- alias: Trigger Trap Schakelaar Links off
  description: ""
  trigger:
    - entity_id: switch.trap_schakelaar_links
      platform: state
      to: "off"
  condition: []
  action:
    - service: homeassistant.turn_off
      entity_id: group.lampen_boven

################################################################################

- alias: Trigger Trap Schakelaar Rechts on
  description: ""
  trigger:
    - entity_id: switch.trap_schakelaar_rechts
      platform: state
      to: "on"
  condition: []
  action:
    - service: homeassistant.turn_on
      entity_id: group.lampen_beneden

- alias: Trigger Trap Schakelaar Rechts off
  description: ""
  trigger:
    - entity_id: switch.trap_schakelaar_rechts
      platform: state
      to: "off"
  condition: []
  action:
    - service: homeassistant.turn_off
      entity_id: group.lampen_beneden
