- id: '1660306042772'
  alias: Frigate Notifications - Tuin
  description: ''
  use_blueprint:
    path: hunterjm/frigate_notification.yaml
    input:
      camera: tuin
      notify_device: ea07a2d0f491470fbdfbc90cbbf97f4f
      base_url: https://ha.vels.online
      labels:
      - person
      presence_filter: person.eddie
- id: '1656000309266'
  alias: push HA configuration to GitHub repo
  description: ''
  trigger:
  - at: '15:10:00'
    platform: time
  action:
    service: shell_command.push_to_github
- id: '1660308585857'
  alias: Frigate Notifications - Voordeur
  description: ''
  use_blueprint:
    path: hunterjm/frigate_notification.yaml
    input:
      camera: voordeur
      notify_device: ea07a2d0f491470fbdfbc90cbbf97f4f
      base_url: https://ha.vels.online
      labels:
      - person
      presence_filter: person.eddie
