- id: '1597588973825'
  alias: Accu weerstation
  description: ''
  trigger:
  - above: '4.2'
    entity_id: sensor.weerstation_accu_spanning
    for: '1'
    platform: numeric_state
  - below: '3'
    entity_id: sensor.weerstation_accu_spanning
    for: '1'
    platform: numeric_state
  condition: []
  action:
  - data:
      data:
        push:
          sound:
            name: default
      message: Accu spanning weerstation buiten grenzen
    service: notify.telegram_eddie
    
    
    
    
- id: '1656000309259'
  alias: Start Backup NUC
  description: ''
  trigger:
  - platform: time
    at: '11:00:00'
  condition: []
  action: []
  mode: single
- id: '1656000537617'
  alias: Start Backup NUC
  description: ''
  trigger:
  - platform: time
    at: '11:00:00'
  condition: []
  action:
  - service: homeassistant.turn_on
    entity_id: switch.kodi_aanzetten
  mode: single




