- id: '1656000309266'
  alias: push HA configuration to GitHub repo
  description: ''
  trigger:
  - at: '15:10:00'
    platform: time
  action:
    service: shell_command.push_to_github
- id: '1702651345928'
  alias: Kertverlichting aan in het donker
  description: ''
  trigger:
  - platform: state
    entity_id:
    - input_select.schemer_buiten
    from: Licht
    to: Donker
  condition:
  - condition: state
    entity_id: person.eddie
    state: home
  action:
  - service: switch.turn_on
    target:
      entity_id: switch.kerstverlichting
    data: {}
  mode: single
- id: '1705342815614'
  alias: Frigate Notifications Tuin
  description: ''
  use_blueprint:
    path: SgtBatten/Stable.yaml
    input:
      camera: camera.tuin
      notify_device: ea07a2d0f491470fbdfbc90cbbf97f4f
      base_url: https://ha.vels.online
      alert_once: true
      ios_live_view: true
      labels:
      - person
      presence_filter: group.presence
- id: '1705342898510'
  alias: Frigate Notifications Voordeur
  description: ''
  use_blueprint:
    path: SgtBatten/Stable.yaml
    input:
      camera: camera.voordeur
      notify_device: ea07a2d0f491470fbdfbc90cbbf97f4f
      base_url: https://ha.vels.online
      alert_once: true
      ios_live_view: true
      presence_filter: group.presence
- id: '1705343514704'
  alias: Overloop Motion
  description: ''
  use_blueprint:
    path: freakshock88/motion_illuminance_activated_entity.yaml
    input:
      motion_sensor: light.pir_overloop_basic
      target_entity: light.overloop_2
      no_motion_wait: input_number.overloop_turnoff_waittime
- id: '1705860970036'
  alias: Low battery level detection & notification for all battery sensors
  description: ''
  use_blueprint:
    path: sbyx/low-battery-level-detection-notification-for-all-battery-sensors.yaml
    input:
      threshold: 35
      time: '20:00:00'
      actions:
      - service: notify.mobile_app_reyhzhao
        metadata: {}
        data:
          title: Low battery
          message: 'Sensors: {{sensors}}'
- id: '1706960896709'
  alias: IOS-Action - Alarm Arm Away
  description: ''
  trigger:
  - platform: event
    event_type: ios.action_fired
    event_data:
      actionName: Alarm - Arm Away
  action:
  - service: alarmo.arm
    metadata: {}
    data:
      mode: away
      skip_delay: true
      force: true
      entity_id: alarm_control_panel.alarmo
  initial_state: true
  mode: single
- id: '1706961147636'
  alias: IOS-Action - Alarm Disarm
  description: ''
  trigger:
  - platform: event
    event_type: ios.action_fired
    event_data:
      actionName: Alarm - Disarm
  action:
  - service: alarm_control_panel.alarm_disarm
    data:
      entity_id: alarm_control_panel.alarmo
  initial_state: true
  mode: single
- id: '1726247369020'
  alias: Spotify - Move Audio to Kantoor
  description: ''
  trigger:
  - platform: state
    entity_id:
    - binary_sensor.motion_kantoor
    from: 'off'
    to: 'on'
  condition:
  - condition: state
    entity_id: media_player.spotify
    state: playing
  action:
  - action: media_player.select_source
    metadata: {}
    data:
      source: raspotify (raspotify)
    target:
      entity_id: media_player.spotify
  mode: single
- id: '1726247506740'
  alias: Spotify - Move Audio to Woonkamer
  description: ''
  trigger:
  - platform: state
    entity_id:
    - binary_sensor.pir_woonkamer2_home_security_motion_detection
    from: 'off'
    to: 'on'
  condition:
  - condition: state
    entity_id: media_player.spotify
    state: playing
  - condition: or
    conditions:
    - condition: state
      entity_id: binary_sensor.motion_overloop
      state: 'on'
    - condition: state
      entity_id: binary_sensor.motion_gang
      state: 'on'
  action:
  - action: media_player.select_source
    metadata: {}
    data:
      source: woonkamer
    target:
      entity_id: media_player.spotify
  mode: single
- id: '1736180505596'
  alias: Random Away Lights
  description: ''
  triggers:
  - minutes: /15
    trigger: time_pattern
  conditions:
  - condition: state
    entity_id: group.presence
    state: not_home
  - condition: sun
    after: sunset
    after_offset: -00:30:00
  - condition: time
    before: '22:30:00'
  actions:
  - delay: 00:{{ '{:02}'.format(range(0,30) | random | int) }}:00
  - data_template:
      entity_id: input_text.light_to_switch
      value: '{{ state_attr(''group.simulation_lights'',''entity_id'') | random }}'
    action: input_text.set_value
  - data_template:
      entity_id: '{{states(''input_text.light_to_switch'')}}'
    action: homeassistant.toggle
  mode: single
  initial_state: true
- id: '1739122459288'
  alias: Notification of camera events
  triggers:
  - topic: frigate/events
    trigger: mqtt
  conditions:
  - condition: template
    value_template: '{{ trigger.payload_json[''type''] == ''end'' }}'
  - condition: template
    value_template: '{{ trigger.payload_json[''after''][''entered_zones''] | length
      > 0 }}'
  actions:
  - variables:
      event_id: '{{ trigger.payload_json[''after''][''id''] }}'
      camera: '{{ trigger.payload_json[''after''][''camera''] }}'
      label: '{{ trigger.payload_json[''after''][''label''] }}'
  - wait_for_trigger:
    - topic: frigate/tracked_object_update
      value_template: '{{ value_json[''type''] == ''description'' and value_json[''id'']
        == event_id }}

        '
      variables:
        event_id: '{{ event_id }}'
      trigger: mqtt
    timeout: '15'
    continue_on_timeout: true
  - choose:
    - conditions:
      - condition: template
        value_template: '{{ wait.trigger is not none }}'
      sequence:
      - variables:
          description: '{{ wait.trigger.payload_json[''description''] }}'
      - data:
          message: '{{ description }} - View Snapshot: https://pub.domain.com/api/frigate/notifications/{{
            event_id }}/snapshot.jpg - View clip: https://pub.domain.com/api/frigate/notifications/{{
            event_id }}/clip.mp4

            '
          data:
            verify_ssl: false
            urls:
            - http://10.0.1.11:8123/api/frigate/notifications/{{ event_id }}/thumbnail.jpg
        action: notify.signal
      - data:
          url: http://10.0.1.11:8123/api/frigate/notifications/{{ event_id }}/thumbnail.jpg
          caption: "<b>Camera Alert</b> \U0001F6A8\n├ <i>Camera:</i> {{ camera }}
            \n└ <i>Event:</i> ┐\n{{ description }}\n\n<a href=\"https://pub.domain.com/api/frigate/notifications/{{
            event_id }}/snapshot.jpg\">\U0001F4F7 View Snapshot \U0001F4F7</a>\n\n<a
            href=\"https://pub.domain.com/api/frigate/notifications/{{ event_id }}/clip.mp4\">\U0001F3A5
            View Clip \U0001F3A5</a>\n"
          parse_mode: html
          disable_web_page_preview: true
        action: telegram_bot.send_photo
    default:
    - action: notify.notify
      data:
        message: Camera triggerd
    - data:
        target: -123456789
        url: http://10.0.1.11:8123/api/frigate/notifications/{{ event_id }}/thumbnail.jpg
        caption: "<b>Camera Alert</b> \U0001F6A8\n├ <i>Camera:</i> {{ camera }}\n└
          <i>Event:</i> {{ label }} detected\n\n<a href=\"https://pub.domain.com/api/frigate/notifications/{{
          event_id }}/snapshot.jpg\">\U0001F4F7 View Snapshot \U0001F4F7</a>\n\n<a
          href=\"https://pub.domain.com/api/frigate/notifications/{{ event_id }}/clip.mp4\">\U0001F3A5
          View Clip \U0001F3A5</a>\n"
        parse_mode: html
        disable_web_page_preview: true
      action: telegram_bot.send_photo
  - delay: '00:00:01.2'
  mode: queued
