homeassistant:
  customize: !include customize.yaml
  latitude: !secret homeassistant_latitude
  longitude: !secret homeassistant_longitude
  elevation: !secret homeassistant_elevation
  time_zone: Europe/Amsterdam
  country: "NL"
  packages: !include_dir_named packages
  external_url: !secret external_url
  internal_url: !secret internal_url

# Configure a default setup of Home Assistant (frontend, api, etc)
default_config:

frontend:
  #javascript_version: latest

http:
  use_x_forwarded_for: true

  trusted_proxies:
    - !secret proxy_host
    - !secret proxy_host2
    - !secret proxy_host3

logger: !include logger.yaml

notify:
  - platform: group
    name: all_contacts
    services:
      - service: mobile_app_reyhzhao

mobile_app:

# sabnzbd:
#   api_key: !secret sabnzbd_api

ios:

# Text to speech
tts:
  - platform: google_translate

remote:

input_boolean:
  spotify_shuffle:
    name: Shuffle
    icon: mdi:shuffle-variant

  nachtstand:
    name: Nachtstand
    initial: off
    icon: mdi:weather-night

input_text:
  light_to_switch:
    name: Lights to switch
    initial: "off"

input_number:
  spotify_volume:
    name: Volume
    icon: mdi:volume-high
    initial: 100
    min: 0
    max: 100
    step: 1

shell_command:
  push_to_github: /root/config/gitupdate.sh

media_player:
  - platform: yamaha
    host: !secret yamaha_host
    source_names:
      HDMI5: Kodi

zone:
  - name: Home
    radius: 200
    latitude: !secret home_lat
    longitude: !secret home_lon

  - name: Werk Eddie
    latitude: !secret work_eddie_lat
    longitude: !secret work_eddie_lon
    radius: 400

alarm_control_panel:
  - platform: manual
    code_arm_required: false
    #delay_time: 10
    delay_time: 0
    #pending_time: 10
    arming_time: 0
    trigger_time: 4
    disarmed:
      trigger_time: 0
    armed_home:
      arming_time: 0
      delay_time: 0

switch:
  - platform: flux
    lights:
      - light.woonkamer
    name: Fluxer
    start_time: "7:00"
    stop_time: "23:00"
    start_colortemp: 5000
    sunset_colortemp: 3000
    stop_colortemp: 1900
    brightness: 200
    disable_brightness_adjust: false
    mode: xy
    transition: 30
    interval: 60

  - platform: wake_on_lan
    name: TV aanzetten
    host: !secret bravia_tv_host
    mac: 94:53:30:60:EB:SF

plant:
  chamaedorea:
    sensors:
      moisture: sensor.plant_sensor_0414_moisture
      temperature: sensor.plant_sensor_0414_temperature
      conductivity: sensor.plant_sensor_0414_conductivity
      brightness: sensor.plant_sensor_0414_illuminance

wake_on_lan:

device_tracker:
  - platform: bluetooth_le_tracker

binary_sensor:
  - platform: template
    sensors:
      person_eddie_url:
        value_template: "{{ state_attr('person.eddie', 'latitude') and state_attr('person.eddie', 'longitude') }}"
        attribute_templates:
          url: >
            {% set lat = state_attr('person.eddie', 'latitude') %}
            {% set lon = state_attr('person.eddie', 'longitude') %}
            {% set zoom = 3 %}
            https://embed.waze.com/nl/iframe?zoom={{ zoom }}&lat={{ lat }}&lon={{ lon }}&pin=1&desc=1

light:
  - platform: limitlessled
    bridges:
      - host: !secret limitless_host
        version: 5
        port: 8899
        groups:
          - number: 1
            name: Milight 1
            fade: true
          - number: 2
            name: Milight 2
            fade: true
          - number: 3
            name: Milight 3
            fade: true
          - number: 4
            name: Milight 4
            fade: true

mqtt:
  sensor:
    - name: "FaceID Eddie"
      icon: mdi:account
      state_topic: "double-take/matches/eddie"
      json_attributes_topic: "double-take/matches/eddie"
      value_template: "{{ value_json.camera }}"
      availability_topic: "double-take/available"

    - name: "FaceID Simone"
      icon: mdi:account
      state_topic: "double-take/matches/simone"
      json_attributes_topic: "double-take/matches/simone"
      value_template: "{{ value_json.camera }}"
      availability_topic: "double-take/available"

    - name: "Bodemvochtigheid"
      state_topic: esptuin/Soil/Analog
      unit_of_measurement: "%"
      device_class: humidity

  switch:
    - name: zone1_valve
      state_topic: esptuin/Relay02/RL02
      command_topic: esptuin/gpio/14
      payload_on: 1
      payload_off: 0
      optimistic: false
      retain: true
      icon: mdi:valve

    - name: Dust Sensor sleep
      state_topic: espweerstation/gpio/14
      command_topic: espweerstation/gpio/14
      payload_on: 1
      payload_off: 0
      optimistic: false
      retain: true

    - name: Kantoor Dust Sensor sleep
      state_topic: espkantoor/DustSensor/State
      command_topic: espkantoor/gpioo/14/
      payload_on: 1
      payload_off: 0
      optimistic: false
      retain: false

    #####################

    - name: Buitenverlichting
      state_topic: espbuitenverlichting/Relay01/RL01
      command_topic: espbuitenverlichting/gpio/14
      payload_on: 1
      payload_off: 0
      optimistic: false
      retain: true

sensor: !include sensor.yaml

python_script:

group: !include groups.yaml

script: !include scripts.yaml
scene: !include scenes.yaml
recorder: !include recorder.yaml
input_select: !include input_select.yaml
timer: !include timers.yaml

automation ui: !include automations.yaml
automation: !include_dir_merge_list automation/
