
homeassistant:
   customize: !include customize.yaml
   latitude: !secret homeassistant_latitude
   longitude: !secret homeassistant_longitude
   elevation: !secret homeassistant_elevation   
   time_zone: Europe/Amsterdam
   packages: !include_dir_named packages
   external_url: https://ha.noctis-nexus.nl
   internal_url: http://192.168.232.109:8123

# Configure a default setup of Home Assistant (frontend, api, etc)
default_config:

frontend:
  javascript_version: latest

# Uncomment this if you are using SSL/TLS, running in Docker container, etc.
# http:
#   base_url: example.duckdns.org:8123

http:
   use_x_forwarded_for: true      
   
   trusted_proxies: 
      - !secret proxy_host
      


   
logger: !include logger.yaml

influxdb:
  host: !secret influx_host
  database: hass

weather:
  - platform: darksky
    api_key: !secret darksky_api_key


  - platform: smartweather
    api_key: !secret darksky_api_key


  - platform: buienradar
    forecast: true
    name: arnhem
    latitude: !secret homeassistant_latitude
    longitude: !secret homeassistant_longitude

smartweather:
    station_id: 4967
    api_key: 20c70eae-e62f-4d3b-b3a4-8586e90f3ac8

octoprint:
    host: 192.168.232.115
    api_key: !secret octoprint_api
    bed: true
    number_of_tools: 1

telegram_bot:
  - platform: polling
    api_key: !secret telegram_api_key 
    allowed_chat_ids: 
       - !secret telegram_groupid
       - !secret telegram_eddie

notify:
  - name: telegram_group
    platform: telegram
    chat_id: !secret telegram_groupid

  - name: telegram_eddie
    platform: telegram
    chat_id: !secret telegram_eddie

  - platform: group
    name: all_contacts
    services:
      - service: mobile_app_reyhzhao
      - service: telegram_eddie
      - service: mobile_app_esther_s_oneplus_a6003


mobile_app:

sabnzbd:
   api_key: !secret sabnzbd_api
   host: !secret sabnzbd_host
   port: 8085
   sensors:
     - current_status
     - speed
     - queue_size
     - queue_remaining
     - disk_size
     - disk_free
     - queue_count
     - day_size
     - week_size
     - month_size
     - total_size   

discovery:

ios:        

# Text to speech
tts:
  - platform: google_translate

remote:
  - platform: harmony
    name: Harmony
    host: !secret harmony_host
    activity: TV kijken
    
    
#camera:
#  - platform: generic
#    still_image_url: http://192.168.232.106/snap.jpeg
#    stream_source: rtsp://ubnt:ubnt@192.168.232.106:554/s0
#    username: ubnt
#    password: ubnt

camera:
  - platform: uvc
    nvr: 192.168.232.119
    key: !secret unifi_key
    password: !secret unifi_camera

input_boolean:
   spotify_shuffle:
      name: Shuffle
      icon: mdi:shuffle-variant

   nachtstand:
     name: Nachtstand
     initial: off
     icon: mdi:weather-night


input_number:
  spotify_volume:
    name: Volume
    icon: mdi:volume-high
    initial: 100
    min: 0
    max: 100
    step: 1

#tuya:    
#  username: !secret tuya_username
#  password: !secret tuya_password
#  country_code: 1
#  platform: smart_life


spotify:
  client_id: !secret spotify_client_id
  client_secret: !secret spotify_client_secret

media_player:
  - platform: braviatv
    host: !secret bravia_tv_host
    
    
  - platform: androidtv
    name: Android TV Woonkamer
    host: !secret bravia_tv_host

  - platform: kodi
    host: !secret kodi_host
    port: 8080
    tcp_port: 9090
    username: !secret kodi_username
    password: !secret kodi_password
    
  - platform: yamaha
    host: !secret yamaha_host
    source_names:
            HDMI5: Kodi

zone:
  - name: Home
    radius: 500
    latitude: !secret home_lat
    longitude: !secret home_lon
    
  - name: Werk Eddie
    latitude: !secret work_eddie_lat
    longitude: !secret work_eddie_lon
    radius: 400

alarm_control_panel:
  - platform: manual
    #delay_time: 10
    delay_time: 0
    #pending_time: 10
    arming_time: 0
    trigger_time: 4
    disarmed:
      trigger_time: 0
    armed_home:
      arming_time: 0
      delay_time: 0

rfxtrx:
  device: /dev/serial/by-id/usb-RFXCOM_RFXtrx433_A1BFB4H-if00-port0
  debug: True

switch:

  - platform: mqtt
    name: zone1_valve
    state_topic: esptuin/Relay02/RL02
    command_topic: esptuin/gpio/14
    payload_on: 1
    payload_off: 0
    optimistic: false
    retain: true
    icon: mdi:valve

  - platform: mqtt
    name: Dust Sensor sleep
    state_topic: espbuitenluchtkwaliteit/Sleep/State
    command_topic: espbuitenluchtkwaliteit/gpio/14
    payload_on: 1
    payload_off: 0
    optimistic: false
    retain: true    

  - platform: mqtt
    name: Buitenverlichting
    state_topic: espbuitenverlichting/Relay01/RL01    
    command_topic: espbuitenverlichting/gpio/14
    payload_on: 1
    payload_off: 0
    optimistic: false
    retain: true

  - platform: wake_on_lan
    name: Kodi aanzetten
    host: !secret kodi_host
    mac: F4:4D:30:68:9E:9D

  - platform: wake_on_lan
    name: TV aanzetten
    host: !secret bravia_tv_host
    mac: 94:53:30:60:EB:SF

  - platform: rfxtrx
    automatic_add: true
    devices:
       0b11000101bcbd4201010f70:
          name: Schakelaar Keuken
       0b11000201bcbd4202010f70:
          name: Schakelaar Eetkamer
       0b11000201d6cb5b0a010f70:
          name: Schakelaar Kantoor
       0b1100260180ea1e0a010f70:
          name: Schakelaar Trapkast
       0b11001501b34a6a0a010f70:
          name: Schakelaar Woonkamer

netatmo:
  client_id: !secret netatmo_client
  client_secret: !secret netatmo_secret

binary_sensor:
  - platform: smartweather
    monitored_conditions: 
      - raining
      - freezing
      - lightning

  - platform: uptimerobot
    api_key: !secret uptimerobot

  - platform: rfxtrx
    automatic_add: true
    devices:
       0b1100000196772e0a010f70:
          name: Achterdeur
          device_class: door
       0b11000701966e6e0a010f70:
          name: Voordeur
          device_class: door
       0b11000900bfffc60a010f50:
          name: PIR Zolder
          device_class: motion
       0b11000001966e6a0a010f60:
          name: Raam Badkamer
          device_class: window

       0b11002f014ee78a0b010f60:
          name: Schakelaar Nachtkastje L
          #device_class: 

       0b110035014ee78a0c010f60:
          name: Schakelaar Nachtkastje R
          #device_class:

light:
  - platform: rfxtrx
    automatic_add: true  
    devices:
       0710012744090170:
          name: Lamp Trapkast
       0b1100230028d00204010f70:
          name: Verlichting Buiten

  - platform: limitlessled
    bridges:           
       - host: 192.168.200.200
         version: 5
         port: 8899
         groups:
         - number: 1           
           name: Milight 1
           fade: true            
         - number: 2
           name: Milight 2
           fade: true
         - number: 3
           name: Milight 3
           fade: true
         - number: 4
           name: Milight 4
           fade: true

zwave:
  usb_path: /dev/ttyUSB12
  device_config: !include zwave_device_config.yaml
  network_key: !secret zwave_network_key


mqtt:
    broker: 127.0.0.1

sensor: !include sensor.yaml

panel_custom:
  - name: zwavegraph2
    sidebar_title: Z-Wave Graph
    sidebar_icon: mdi:access-point-network
    url_path: zwave


group: !include groups.yaml
automation: !include_dir_merge_list automation/
script: !include scripts.yaml
scene: !include scenes.yaml
recorder: !include recorder.yaml
input_select: !include input_select.yaml
timer: !include timers.yaml
