homeassistant:
  customize: !include customize.yaml
  latitude: !secret homeassistant_latitude
  longitude: !secret homeassistant_longitude
  elevation: !secret homeassistant_elevation
  time_zone: Europe/Amsterdam
  country: "NL"
  packages: !include_dir_named packages
  external_url: !secret external_url
  internal_url: !secret internal_url

# Configure a default setup of Home Assistant (frontend, api, etc)
default_config:

frontend:
  #javascript_version: latest

http:
  use_x_forwarded_for: true

  trusted_proxies:
    - !secret proxy_host
    - !secret proxy_host2
    - !secret proxy_host3

logger: !include logger.yaml

#influxdb:
#  host: !secret influx_host
#  database: hass

# weather:
# - platform: darksky
#   api_key: !secret darksky_api_key

# - platform: buienradar
#   forecast: true
#   name: arnhem
#   latitude: !secret homeassistant_latitude
#   longitude: !secret homeassistant_longitude

#octoprint:
#    host: !secret octoprint_host
#    api_key: !secret octoprint_api
#    bed: true
#    number_of_tools: 1

# matrix:
#   homeserver: !secret matrix_server
#   username: !secret matrix_username
#   password: !secret matrix_password
#   rooms:
#     - !secret matrix_room

notify:
  # - name: matrix_notify
  #   platform: matrix
  #   default_room: !secret matrix_room

  - platform: group
    name: all_contacts
    services:
      - service: mobile_app_reyhzhao
      - service: mobile_app_in2013

mobile_app:

sabnzbd:
  api_key: !secret sabnzbd_api

ios:

# Text to speech
tts:
  - platform: google_translate

remote:

input_boolean:
  spotify_shuffle:
    name: Shuffle
    icon: mdi:shuffle-variant

  nachtstand:
    name: Nachtstand
    initial: off
    icon: mdi:weather-night

input_text:
  light_to_switch:
    name: Lights to switch
    initial: "off"

input_number:
  spotify_volume:
    name: Volume
    icon: mdi:volume-high
    initial: 100
    min: 0
    max: 100
    step: 1

shell_command:
  push_to_github: /root/config/gitupdate.sh

media_player:
  - platform: yamaha
    host: !secret yamaha_host
    source_names:
      HDMI5: Kodi

zone:
  - name: Home
    radius: 200
    latitude: !secret home_lat
    longitude: !secret home_lon

  - name: Werk Eddie
    latitude: !secret work_eddie_lat
    longitude: !secret work_eddie_lon
    radius: 400

alarm_control_panel:
  - platform: manual
    #delay_time: 10
    delay_time: 0
    #pending_time: 10
    arming_time: 0
    trigger_time: 4
    disarmed:
      trigger_time: 0
    armed_home:
      arming_time: 0
      delay_time: 0

# rfxtrx:
#   device: /dev/serial/by-id/usb-RFXCOM_RFXtrx433_A1BFB4H-if00-port0
#   #debug: True
#   automatic_add: true
#   devices:
#     # Schakelaar Nachtkastje L
#     0b11002f014ee78a0b010f60:

#     # Schakelaar Nachtkastje R
#     0b110035014ee78a0c010f60:

#     # Raam Badkamer
#     0b11000001966e6a0a010f60:

#     # PIR Zolder
#     0b11000900bfffc60a010f50:

#     # Voordeur
#     0b11000701966e6e0a010f70:

#     # Achterdeur
#     0b1100000196772e0a010f70:

#     # Lamp Trapkast
#     0b0710012744090170020f70:

#     # Kerstboom
#     #0b11000482bc0cfe04020f70:
#     #  name: Kerstboom

#     0A140F0900020201010000:
#       name: Kerstboom

switch:
  # - platform: rest
  #   name: Unifi Video Recording
  #   method: put
  #   timeout: 300
  #   resource: https://unifi-video.vels.online/api/2.0/camera/625d7028e4b070acfaea534b?apiKey=7OSzSgyShlfENzLaEL9eTc1BgbfWwOMM
  #   body_on: '{ "name": "Camera-Tuin", "recordingSettings": { "channel": "0", "fullTimeRecordEnabled": false,  "motionRecordEnabled": true } }'
  #   body_off: '{ "name": "Camera-Tuin", "recordingSettings": { "channel": "0", "fullTimeRecordEnabled": false,  "motionRecordEnabled": false } }'
  #   is_on_template: "{{ value_json.data.0.recordingSettings.motionRecordEnabled }}"
  #   headers:
  #     Content-Type: application/json
  #   verify_ssl: true

  - platform: flux
    lights:
      - light.woonkamer
    name: Fluxer
    start_time: "7:00"
    stop_time: "23:00"
    start_colortemp: 5000
    sunset_colortemp: 3000
    stop_colortemp: 1900
    brightness: 200
    disable_brightness_adjust: false
    mode: xy
    transition: 30
    interval: 60

  - platform: wake_on_lan
    name: TV aanzetten
    host: !secret bravia_tv_host
    mac: 94:53:30:60:EB:SF

plant:
  areca:
    sensors:
      moisture: sensor.xiaomi_hhccjcy01_moisture
      temperature: sensor.xiaomi_hhccjcy01_temperature
      conductivity: sensor.xiaomi_hhccjcy01_soil_conductivity
      brightness: sensor.xiaomi_hhccjcy01_illuminance

wake_on_lan:

binary_sensor:
  - platform: template
    sensors:
      person_eddie_url:
        value_template: "{{ state_attr('person.eddie', 'latitude') and state_attr('person.eddie', 'longitude') }}"
        attribute_templates:
          url: >
            {% set lat = state_attr('person.eddie', 'latitude') %}
            {% set lon = state_attr('person.eddie', 'longitude') %}
            {% set zoom = 3 %}
            https://embed.waze.com/nl/iframe?zoom={{ zoom }}&lat={{ lat }}&lon={{ lon }}&pin=1&desc=1

light:
  - platform: limitlessled
    bridges:
      - host: !secret limitless_host
        version: 5
        port: 8899
        groups:
          - number: 1
            name: Milight 1
            fade: true
          - number: 2
            name: Milight 2
            fade: true
          - number: 3
            name: Milight 3
            fade: true
          - number: 4
            name: Milight 4
            fade: true

mqtt:
  sensor:
    - name: "FaceID Eddie"
      icon: mdi:account
      state_topic: "double-take/matches/eddie"
      json_attributes_topic: "double-take/matches/eddie"
      value_template: "{{ value_json.camera }}"
      availability_topic: "double-take/available"

    - name: "FaceID Esther"
      icon: mdi:account
      state_topic: "double-take/matches/esther"
      json_attributes_topic: "double-take/matches/esther"
      value_template: "{{ value_json.camera }}"
      availability_topic: "double-take/available"

    - name: "Bodemvochtigheid"
      state_topic: esptuin/Soil/Analog
      unit_of_measurement: "%"
      device_class: humidity

  switch:
    - name: zone1_valve
      state_topic: esptuin/Relay02/RL02
      command_topic: esptuin/gpio/14
      payload_on: 1
      payload_off: 0
      optimistic: false
      retain: true
      icon: mdi:valve

    - name: Dust Sensor sleep
      state_topic: espweerstation/gpio/14
      command_topic: espweerstation/gpio/14
      payload_on: 1
      payload_off: 0
      optimistic: false
      retain: true

    - name: Kantoor Dust Sensor sleep
      state_topic: espkantoor/DustSensor/State
      command_topic: espkantoor/gpioo/14/
      payload_on: 1
      payload_off: 0
      optimistic: false
      retain: false

    #####################

    - name: Buitenverlichting
      state_topic: espbuitenverlichting/Relay01/RL01
      command_topic: espbuitenverlichting/gpio/14
      payload_on: 1
      payload_off: 0
      optimistic: false
      retain: true

sensor: !include sensor.yaml

# panel_custom:
# - name: zwavegraph2
#   sidebar_title: Z-Wave Graph
#   sidebar_icon: mdi:access-point-network
#   url_path: zwave

python_script:

group: !include groups.yaml

script: !include scripts.yaml
scene: !include scenes.yaml
recorder: !include recorder.yaml
input_select: !include input_select.yaml
timer: !include timers.yaml

automation ui: !include automations.yaml
automation: !include_dir_merge_list automation/
