- platform: mqtt_room
  #device_id: "roomAssistant:c814e89f-fc07-4a9f-9202-f812da82f39a"
  device_id: "apple:1006:10-7"
  #device_id: "apple:iphone14-2"
  name: "iPhone Eddie"
  state_topic: "espresense/rooms"
  timeout: 5
  away_timeout: 120 # number of seconds after which the enitity will get status not_home

- platform: mqtt_room
  device_id: "tile:f52f25ee711a"
  name: "Tile Eddie"
  state_topic: "espresense/rooms"
  timeout: 5
  away_timeout: 120 # number of seconds after which the enitity will get status not_home

- platform: mqtt_room
  device_id: "apple:1005:9-12"
  name: "MacBook Eddie"
  state_topic: "espresense/rooms"
  timeout: 5
  away_timeout: 120 # number of seconds after which the enitity will get status not_home

# - platform: mqtt_room
#   device_id: "iBeacon:50765cb7-d9ea-4e21-99a4-fa879613a492-25880-19325"
#   name: "Android Esther"
#   state_topic: "espresense/rooms"
#   timeout: 5
#   away_timeout: 120 # number of seconds after which the enitity will get status not_home

###############################################################
# - platform: mqtt
#   name: "Unifi Camera Gifs"
#   state_topic: "cameras/gifs/Camera Tuin"

- platform: filter
  name: "filterd bodemvochtigheid"
  entity_id: sensor.bodemvochtigheid
  filters:
    - filter: outlier
      window_size: 4
      radius: 4.0
    - filter: lowpass
      time_constant: 10
      precision: 2

# - platform: mqtt
#   state_topic: "monitor/beneden/iphone_eddie"
#   value_template: "{{ value_json.confidence }}"
#   unit_of_measurement: "%"
#   name: "Beneden"

- platform: sonarr
  api_key: !secret sonarr_api
  host: 192.168.232.119
  port: 8989
  days: 2

#    - platform: dsmr_reader

- platform: template
  sensors:
    spotify_volume:
      friendly_name: "Spotify Volume"
      value_template: "{{ states.media_player.spotify.attributes.volume_level }}"
- platform: template
  sensors:
    spotify_shuffle:
      friendly_name: "Spotify Shuffle"
      value_template: "{{ states.media_player.spotify.attributes.shuffle }}"

- platform: template
  sensors:
    spotify_source:
      friendly_name: "Spotify Source"
      value_template: "{{ states.media_player.spotify.attributes.source }}"

- platform: template
  sensors:
    harmony_woonkamer:
      value_template: '{{ state_attr("remote.harmony", "current_activity") }}'
      friendly_name: "Harmony Woonkamer"

- platform: darksky
  api_key: !secret darksky_api_key
  name: dark_sky_forecast
  units: auto
  scan_interval:
    minutes: 720
  forecast:
    - 0
    - 1
    - 2
    - 3
    - 4
    - 5
  monitored_conditions:
    - icon
    - summary
    - temperature_high
    - temperature_low
    - precip_intensity_max
    - precip_probability

- platform: darksky
  api_key: !secret darksky_api_key
  forecast:
    - 0
  hourly_forecast:
    - 0
    - 1
    - 2
    - 3
    - 4
    - 5
    - 6
  language: nl

  monitored_conditions:
    - summary
    - icon
    - nearest_storm_distance
    - alerts
    - precip_intensity
    - precip_probability
    - temperature_high
    - temperature_low

- platform: buienradar
  monitored_conditions:
    - symbol
    - humidity
    - temperature
    - windspeed
    - pressure
    - conditioncode
    - condition
    - conditiondetailed
    - feeltemperature
    - precipitation
    - precipitation_forecast_total
#        - temperature_high
#        - temperature_low

