- alias: Trigger Trapkast on
  description: ''
  trigger:
  - entity_id: switch.schakelaar_trapkast
    platform: state
    to: 'on'
  condition: []
  action:
  - service: homeassistant.turn_on
    entity_id: switch.lamp_trapkast_n


- alias: Trigger Trapkast off
  description: ''
  trigger:
  - entity_id: switch.schakelaar_trapkast
    platform: state
    to: 'off'
  condition: []
  action:
  - service: homeassistant.turn_off
    entity_id: switch.lamp_trapkast_n
