- alias: Notify phone of new movement in backyard
  trigger:
    - platform: state
      entity_id: sensor.unifi_camera_gifs
  #condition:
  #    - condition: state
  #    entity_id: 'device_tracker.zack_phone'
  #    state: 'not_home'
  action:
    - service: notify.ALL_CONTACTS
      data:
        title: "Movement detected!"
        message: "Movement detected in the Backyard!"
        data:
          video:
            - file: /mnt/unify-video/gifs/{{ states.sensor.unifi_camera_gifs.state }}
              caption: "Movement detected in the Backyard!"
