- alias: Trigger Zolder Lamp On
  description: ""

  trigger:
    - platform: state
      entity_id: binary_sensor.motion_zolder_espresense
      to: "on"
    - platform: state
      entity_id: binary_sensor.motion_zolder
      to: "on"
    - platform: state
      entity_id: binary_sensor.schakelaar_trap_links
      to: "on"

  action:
    service: homeassistant.turn_on
    entity_id:
      - switch.lamp_zolder

######################################################################

- alias: Turn off Zolder lamp, x minutes after last movement
  trigger:
    - platform: state
      #entity_id: binary_sensor.motion_zolder
      entity_id: binary_sensor.motion_zolder_espresense
      to: "off"
      for:
        minutes: 5
    - platform: state
      entity_id: binary_sensor.schakelaar_trap_links
      to: "off"

  action:
    service: homeassistant.turn_off
    entity_id:
      - switch.lamp_zolder
