- alias: Trigger Buiten Lamp On
  description: ''
  
  trigger:
  - platform: state
    entity_id: binary_sensor.achterdeur
    to: 'on'

  - platform: state
    entity_id: person.eddie, person.esther
    to: 'home'
    
  condition:
    condition: state
    entity_id: input_select.schemer_buiten
    state: Donker
    
  action:
    - service: homeassistant.turn_on
      entity_id: light.buiten

    - service: timer.start
      data:
        entity_id: timer.buiten


######################################################################


- alias: Turn off Buiten lamp, x minutes after last movement
  trigger:
    platform: event
    event_type: timer.finished
    event_data:
      entity_id: timer.buiten

  action:
    service: homeassistant.turn_off
    entity_id: light.buiten
