
######################################################################

- alias: Trigger Kantoor Lamp On
  description: ''

  trigger:
  - platform: state
    entity_id: binary_sensor.motion_kantoor
    to: 'on'

  - platform: state
    entity_id: switch.schakelaar_kantoor
    to: 'on'

  condition:
    condition: state
    entity_id: input_select.schemer_kantoor
    state: 'Donker'

  action:
    service: homeassistant.turn_on
    entity_id:
       - light.kantoor
       - switch.schakelaar_kantoor
       - switch.kantoor_sfeerverlichting


######################################################################


- alias: Trigger Kantoor Lamp On als het donker wordt
  description: ''

  trigger:
    - platform: state
      entity_id: switch.schemer_kantoor
      to: 'Donker'

  condition:
    condition: template
    value_template: "{{ states.binary_sensor.motion_kantoor.attributes['No motion since']|int  < 180  }}"

  action:
    service: homeassistant.turn_on
    entity_id:
       - light.kantoor
       - switch.schakelaar_kantoor
       - switch.kantoor_sfeerverlichting


######################################################################


- alias: Turn off Kantoor lamp, x minutes after last movement
  trigger:
    - platform: state
      entity_id: binary_sensor.motion_kantoor
      to: 'off'
      for:
        minutes: 5

    - platform: state
      entity_id: switch.schakelaar_kantoor
      to: 'off'       
      
  action:
    service: homeassistant.turn_off
    entity_id: 
       - light.kantoor
       - switch.schakelaar_kantoor
       - switch.kantoor_sfeerverlichting
