







- id: '1656000309266'
  alias: push HA configuration to GitHub repo
  description: ''
  
  trigger:
  # Everyday at 23:23:23 time
  - at: '15:10:00'
    platform: time
  action:
    service: shell_command.push_to_github







