######################################################################

# Trigger iemand gaat slapen
- alias: Trigger iemand gaat slapen
  description: "Trigger als iemand gaat slapen, check of nachtstand aan moet."

  triggers:
    trigger: state
    entity_id:
      - input_select.status_eddie
      # - input_select.status_esther

  condition:
    condition: or
    conditions:
      # # Iedereen thuis en iedereen slaapt
      # - condition: and
      #   conditions:
      #     - condition: state
      #       entity_id: person.eddie
      #       state: "home"
      #     - condition: state
      #       entity_id: person.simone
      #       state: "home"
      #     - condition: state
      #       entity_id: input_select.status_eddie
      #       state: "Slaapt"
      #     - condition: state
      #       entity_id: input_select.status_simone
      #       state: "Slaapt"

      # Alleen Eddie thuis en Eddie slaapt
      - condition: and
        conditions:
          - condition: state
            entity_id: person.eddie
            state: "home"
          # - condition: state
          #   entity_id: person.simone
          #   state: "not_home"

          - condition: state
            entity_id: input_select.status_eddie
            state: "Slaapt"

      # # Alleen simone thuis en simone slaapt
      # - condition: and
      #   conditions:
      #     - condition: state
      #       entity_id: person.eddie
      #       state: "not_home"
      #     - condition: state
      #       entity_id: person.simone
      #       state: "home"

      #     - condition: state
      #       entity_id: input_select.status_eddie
      #       state: "Slaapt"

  action:
    - action: homeassistant.turn_on
      entity_id:
        - input_boolean.nachtstand

######################################################################

# Trigger iemand wordt wakker
- alias: Trigger iemand wordt wakker
  description: "Trigger als iemand wakker wordt, check of nachtstand uit moet."

  triggers:
    trigger: state
    entity_id:
      - input_select.status_eddie
      # - input_select.status_simone
    to: "Wakker"

  action:
    - action: homeassistant.turn_off
      entity_id:
        - input_boolean.nachtstand

######################################################################

# Nachtstand ingeschakeld
- alias: Nachtstand ingeschakeld
  description: ""

  trigger:
    trigger: state
    entity_id: input_boolean.nachtstand
    to: "on"

  actions:
    - action: homeassistant.turn_off
      entity_id:
        - group.all_lights
        - switch.lamp_gang
        - light.overloop
        - automation.trigger_woonkamer_lamp_motion
        - switch.kerstverlichting_buiten
        - switch.mmwave_sensor
        - binary_sensor.motion_woonkamer_mmwaveradar
        - switch.kerstverlichting

    - action: alarmo.arm
      data:
        entity_id: alarm_control_panel.alarmo
        mode: night
        skip_delay: true
        force: true

######################################################################

# Nachtstand uitgeschakeld
- alias: Nachtstand uitgeschakeld
  description: "Nachtstand uitgeschakeld"

  triggers:
    trigger: state
    entity_id: input_boolean.nachtstand
    to: "off"

  actions:
    - action: homeassistant.turn_on
      entity_id:
        - automation.trigger_woonkamer_lamp_motion
        - switch.mmwave_sensor

    - action: alarmo.disarm
      data:
        entity_id: alarm_control_panel.alarmo

######################################################################

# Reset slaap states smiddags.
- alias: Reset nachtstand overdag.
  description: "Reset nachtstand overdag."

  triggers:
    trigger: time
    at: "08:00:00"
  actions:
    - action: homeassistant.turn_off
      entity_id: switch.schakelaar_nachtstand

    - action: input_select.select_option
      data_template:
        entity_id: input_select.status_eddie
        option: "Wakker"

    # - service: input_select.select_option
    #   data_template:
    #     entity_id: input_select.status_simone
    #     option: "Wakker"
