automation:
   - alias: 'Rainy Day'
     trigger:
        - platform: state
          entity_id: sensor.precip_intensity
          to: 'rain'
     condition:
       - condition: state
         entity_id: group.presence
         state: 'home'
        
     action:
        - service: notify.mobile_app_reyhzhao
          data:
             message: Het gaat zo regenen.    