- alias: Trigger Woonkamer Lamp motion
  description: ''
  
  trigger:
  - platform: state
    entity_id: 
      - binary_sensor.achterdeur
      - binary_sensor.motion_woonkamer1 
      - binary_sensor.motion_woonkamer2
    to: 'on'  
      
  condition:
    condition: state
    entity_id: input_select.schemer_buiten
    state: 'Donker'  
  

  action:
  - service: homeassistant.turn_on
    entity_id:
       - switch.schakelaar_woonkamer

  - service: homeassistant.turn_on
    data_template:
      entity_id: light.woonkamer
      brightness: >
        {% if states.media_player.android_tv_woonkamer == 'playing' %}
        25
        {% elif states.media_player.kodi == 'playing' %}
        25
        {% elif now().strftime('%H')| int >= 21 %}
        100
        {% elif now().strftime('%H')| int < 7 %}
        100
        {% elif now().strftime('%H')| int >= 7 %}
        255
        {% endif %}
       
  - service: timer.start
    data:
      entity_id: timer.woonkamer       


######################################################################

- alias: Trigger Woonkamer Lamp schakelaar
  description: ''

  trigger:
  - platform: state
    entity_id:
      - switch.schakelaar_woonkamer
    to: 'on'

  action:
  - service: homeassistant.turn_on
    entity_id:
       - switch.schakelaar_woonkamer

  - service: homeassistant.turn_on
    data_template:
      entity_id: light.woonkamer
      brightness: >
        {% if states.media_player.android_tv_woonkamer == 'playing' %}
        25
        {% elif states.media_player.kodi == 'playing' %}
        25
        {% elif now().strftime('%H')| int >= 21 %}
        100
        {% elif now().strftime('%H')| int < 7 %}
        100
        {% elif now().strftime('%H')| int >= 7 %}
        255
        {% endif %}

  - service: timer.start
    data:
      entity_id: timer.woonkamer


######################################################################

- alias: Turn off Woonkamer lamp door schakelaar
  trigger:
    - platform: state
      entity_id: switch.schakelaar_woonkamer
      to: 'off'     
      
  action:
  - service: homeassistant.turn_off
    entity_id: light.woonkamer
    
  - service: timer.stop
    data:
      entity_id: timer.woonkamer  

######################################################################

- alias: Turn off Woonkamer lamp, x minutes after last movement
  trigger:
    platform: event
    event_type: timer.finished
    event_data:
      entity_id: timer.woonkamer     
      
  action:
    service: homeassistant.turn_off
    entity_id: 
       - light.woonkamer
       - switch.schakelaar_woonkamer
       
