#============================================================================
#=== Not that I don't trust my programming but...
#===   1. Turn off valves and schedules when master control switch is off
#===   2. Turn off all valves when HA starts
#===   3. Don't allow more than one valve on at one time
#===   4. Turn off valve 1 to 4 if it is on for longer than 30 minutes
#===      Turn off valve 5 if it is on for longer than 59 minutes
#=== Better safe than sorry!
#============================================================================

#================
#=== Automations
#================
automation:

  #====================================================================
  #=== Master Control Switch
  #=== Turn off valves and schedules when master control switch is off
  #====================================================================
  - alias: Irrigation Failsafe - Master Control Switch
    trigger:
    - platform: state
      entity_id: input_boolean.irrigation_master_control_switch
      to: 'off'

    - platform: homeassistant
      event: start

    action:
    - service: homeassistant.turn_off
      entity_id:
        - input_boolean.cycle1_manual_run
        - input_boolean.cycle2_manual_run    
        - switch.zone1_valve


  #==================================================================
  #=== Don't allow more than one valve on at one time.
  #=== And
  #=== Turn off valve 1 to 4 if it is on for longer than 30 minutes.
  #=== Turn off valve 5 if it is on for longer than 59 minutes.
  #==================================================================
  #=== Valve 1 ON
  - alias: Irrigation Failsafe - Valve 1 On
    trigger:
    - platform: state
      entity_id:
      - switch.zone1_valve
      to: 'on'

    action:

    - wait_template: "{{ is_state('switch.zone1_valve', 'off') }}"
      timeout: '00:30:15'

    - service: homeassistant.turn_off
      entity_id: switch.zone1_valve



